"""Initial Phase 1 schema

Revision ID: c5792a705f1f
Revises: 
Create Date: 2026-09-06 01:32:07.997015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5792a705f1f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('TEACHER', 'STUDENT', 'ADMIN', name='userrole', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('student_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('student_id_number', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('enrollment_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_profiles_student_id_number'), 'student_profiles', ['student_id_number'], unique=True)
    op.create_index(op.f('ix_student_profiles_user_id'), 'student_profiles', ['user_id'], unique=True)
    op.create_table('teacher_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_profiles_employee_id'), 'teacher_profiles', ['employee_id'], unique=True)
    op.create_index(op.f('ix_teacher_profiles_user_id'), 'teacher_profiles', ['user_id'], unique=True)
    op.create_table('classrooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('course_code', sa.String(length=50), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('livekit_room_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classrooms_course_code'), 'classrooms', ['course_code'], unique=False)
    op.create_index(op.f('ix_classrooms_livekit_room_name'), 'classrooms', ['livekit_room_name'], unique=True)
    op.create_index(op.f('ix_classrooms_teacher_id'), 'classrooms', ['teacher_id'], unique=False)
    op.create_table('face_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('embedding_dim', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_face_embeddings_student_id'), 'face_embeddings', ['student_id'], unique=False)
    op.create_table('class_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('classroom_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='sessionstatus', native_enum=False), nullable=False),
    sa.Column('scheduled_start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_sessions_classroom_id'), 'class_sessions', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_class_sessions_status'), 'class_sessions', ['status'], unique=False)
    op.create_table('attendance_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'LATE', name='attendancestatus', native_enum=False), nullable=False),
    sa.Column('marked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['class_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_records_session_id'), 'attendance_records', ['session_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_student_id'), 'attendance_records', ['student_id'], unique=False)
    op.create_table('class_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['class_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_reports_session_id'), 'class_reports', ['session_id'], unique=True)
    op.create_table('distraction_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['class_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distraction_events_session_id'), 'distraction_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_distraction_events_student_id'), 'distraction_events', ['student_id'], unique=False)
    op.create_table('engagement_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['class_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engagement_metrics_session_id'), 'engagement_metrics', ['session_id'], unique=False)
    op.create_index(op.f('ix_engagement_metrics_student_id'), 'engagement_metrics', ['student_id'], unique=False)
    op.create_table('facial_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('sampled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dominant_emotion', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['class_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facial_analyses_session_id'), 'facial_analyses', ['session_id'], unique=False)
    op.create_index(op.f('ix_facial_analyses_student_id'), 'facial_analyses', ['student_id'], unique=False)
    op.create_table('sentiment_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['class_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentiment_analyses_session_id'), 'sentiment_analyses', ['session_id'], unique=False)
    op.create_index(op.f('ix_sentiment_analyses_user_id'), 'sentiment_analyses', ['user_id'], unique=False)
    op.create_table('session_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('TEACHER', 'STUDENT', 'ADMIN', name='userrole', native_enum=False), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['class_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_participants_session_id'), 'session_participants', ['session_id'], unique=False)
    op.create_index(op.f('ix_session_participants_user_id'), 'session_participants', ['user_id'], unique=False)
    op.create_table('speech_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('sampled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('speech_emotion', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['session_participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['class_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_speech_analyses_participant_id'), 'speech_analyses', ['participant_id'], unique=False)
    op.create_index(op.f('ix_speech_analyses_session_id'), 'speech_analyses', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_speech_analyses_session_id'), table_name='speech_analyses')
    op.drop_index(op.f('ix_speech_analyses_participant_id'), table_name='speech_analyses')
    op.drop_table('speech_analyses')
    op.drop_index(op.f('ix_session_participants_user_id'), table_name='session_participants')
    op.drop_index(op.f('ix_session_participants_session_id'), table_name='session_participants')
    op.drop_table('session_participants')
    op.drop_index(op.f('ix_sentiment_analyses_user_id'), table_name='sentiment_analyses')
    op.drop_index(op.f('ix_sentiment_analyses_session_id'), table_name='sentiment_analyses')
    op.drop_table('sentiment_analyses')
    op.drop_index(op.f('ix_facial_analyses_student_id'), table_name='facial_analyses')
    op.drop_index(op.f('ix_facial_analyses_session_id'), table_name='facial_analyses')
    op.drop_table('facial_analyses')
    op.drop_index(op.f('ix_engagement_metrics_student_id'), table_name='engagement_metrics')
    op.drop_index(op.f('ix_engagement_metrics_session_id'), table_name='engagement_metrics')
    op.drop_table('engagement_metrics')
    op.drop_index(op.f('ix_distraction_events_student_id'), table_name='distraction_events')
    op.drop_index(op.f('ix_distraction_events_session_id'), table_name='distraction_events')
    op.drop_table('distraction_events')
    op.drop_index(op.f('ix_class_reports_session_id'), table_name='class_reports')
    op.drop_table('class_reports')
    op.drop_index(op.f('ix_attendance_records_student_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_session_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_class_sessions_status'), table_name='class_sessions')
    op.drop_index(op.f('ix_class_sessions_classroom_id'), table_name='class_sessions')
    op.drop_table('class_sessions')
    op.drop_index(op.f('ix_face_embeddings_student_id'), table_name='face_embeddings')
    op.drop_table('face_embeddings')
    op.drop_index(op.f('ix_classrooms_teacher_id'), table_name='classrooms')
    op.drop_index(op.f('ix_classrooms_livekit_room_name'), table_name='classrooms')
    op.drop_index(op.f('ix_classrooms_course_code'), table_name='classrooms')
    op.drop_table('classrooms')
    op.drop_index(op.f('ix_teacher_profiles_user_id'), table_name='teacher_profiles')
    op.drop_index(op.f('ix_teacher_profiles_employee_id'), table_name='teacher_profiles')
    op.drop_table('teacher_profiles')
    op.drop_index(op.f('ix_student_profiles_user_id'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_student_id_number'), table_name='student_profiles')
    op.drop_table('student_profiles')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
